### ISSUE TITLE
3011 "接口不支持apikey请求方式"

### ISSUE THREAD

**Issue by MaxTan** [Biboxcom/api-sample#5]
调用普通账户资产接口
POST https://api.bibox.com/v1/transfer

按照文档来调用，报"接口不支持apikey请求方式"什么鬼？

**Comment by asvenslee** [comment]
{"error":{"code":"3011","msg":"接口不支持apikey请求方式"}}  仔仔细细检查了几遍，感觉不是我写的有问题

**Comment by asvenslee** [comment]
普通账户资产
POST https://api.bibox.com/v1/transfer
请求参数：
cmd: "transfer/assets"
body: {
    select       //可选，1-请求所有币种资产明细，不传-各币种总资产合计
}
这个接口有问题，希望尽快解决

**Comment by MaxTan** [comment]
@asvenslee 
兄弟，这个问题我找到原因了， cmds接受的是一个字符串，不是json object。 他们文档这点没写清楚
